### ISSUE TITLE
error in line 34

### ISSUE THREAD

**Issue by Pepper9881** [jilleb/odis2vcp#1]
python odis2vcp.py -i arbeits_.xml -d Tiguan_06D_ALL
 File "odis2vcp.py", line 34
   print " Extracting raw data to \"%s\"" % filename
                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(" Extracting raw data to \"%s\"" % filename)?

**Comment by Mastahh** [comment]
I have created a PR which is fixing this issue.
